# Environment setup - bash version
#
# DO NOT edit this file
#
# Instead, create your own file called environment_local.sh, and
# export any environment variables you wish to change there. The end
# of this script sources environment_local.sh for you.

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
export PYTHONPATH=$DIR/modules/:$PYTHONPATH
export PATH=$DIR/tools/:$PATH

if [ -z "$HALODB_ROOT" ]; then
  export HALODB_ROOT=/nobackupp8/mtremmel/Romulus/
fi

if [ -z "$HALODB_DEFAULT_DB" ]; then
    export HALODB_DEFAULT_DB=/nobackupp8/mtremmel/DataBaseFiles/data_romulus8.db
fi

if [[ -e enivronment_local.sh ]]
then
    source environment_local.sh
fi
